### ISSUE TITLE
Dockerfile ENV paths for EUTelescope

### ISSUE THREAD

**Issue by tbisanz** [duartej/dockerfiles-eudaqv1#6]
Hey,

Out of curiosity I went through your repo - very nice work :)! If you use the newest ilcinstall branch though, you'll need to update some paths, I bumped the GBL and Millepede versions!

Check one of the EUTelescope [Dockerfiles](https://github.com/eutelescope/eutelescope/blob/master/docker/ArchLinux/Dockerfile)!

Well, simply for building EUDAQ it won't matter, but why have it wrong when it can be correct as well!

**Comment by duartej** [comment]
Thanks @tbisanz for checking this. Commit 9a0df4a incorporates the new versions following your Dockerfiles :)
